name: CI Workflow

# Disparadores: Ejecutar el workflow cuando se haga push o se cree un pull request en la rama main
on:
  workflow_dispatch:

# Definir los trabajos que se ejecutarán
jobs:
  build:
    # En qué sistema operativo se ejecutará (Ubuntu)
    runs-on: ubuntu-latest

    # Pasos del workflow
    steps:
      # Paso 1: Usar la acción para configurar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo "hola sebas"
          
      # Notify Microsoft Teams after the build
      - name: Send message to Microsoft Teams
        if: success()  # Only send if the previous steps succeeded
        run: |
          curl -H 'Content-Type: application/json' \
               -d '{"text": "✅ Build succeeded on branch: ${{ github.ref_name }}"}' \
               ${{ secrets.TEAMS_WEBHOOK_URL }}
