name: CI Workflow

# Disparadores: Ejecutar el workflow cuando se haga push o se cree un pull request en la rama main
on:
  workflow_dispatch:

# Definir los trabajos que se ejecutarán
jobs:
  build:
    # En qué sistema operativo se ejecutará (Ubuntu)
    runs-on: ubuntu-latest

    # Pasos del workflow
    steps:
      # Paso 1: Usar la acción para configurar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo "hola sebas"
